# Generated by Django 2.1 on 2018-08-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180829_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgUrl',
            field=models.ImageField(default='0', upload_to='PostImg'),
        ),
    ]
